# Generated by Django 3.1.5 on 2021-01-29 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Video_App', '0003_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='Detail',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='details',
            new_name='detail',
        ),
    ]
