# Generated by Django 3.1.5 on 2021-01-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Video_App', '0004_auto_20210128_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='image',
            field=models.ImageField(upload_to='images/%y'),
        ),
    ]
