# Generated by Django 3.1.5 on 2021-01-29 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Video_App', '0006_post_postimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='post',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
