# Generated by Django 3.1.5 on 2021-01-29 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Video_App', '0007_auto_20210129_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='caption',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='caption',
            field=models.CharField(max_length=200),
        ),
    ]
